### ISSUE TITLE
Loading servers error: "Certificate pinning failure"

### ISSUE THREAD

**Issue by gilpas28** [farimarwat/Internet-Speed-Test#7]
This is the error message:

`Certificate pinning failure!
                                                                           Peer certificate chain:
                                                                             sha256/UkzhMfZXPOrDcz9WVR0k6OVb6X7unkjq2Jrz+BGca4g=: CN=www.speedtest.net
                                                                             sha256/J2/oqMTsdhFWW/n85tys6b4yDBtb6idZayIEBx7QTxA=: CN=E1,O=Let's Encrypt,C=US
                                                                             sha256/diGVwiVYbubAI3RW4hB9xU8e/CH2GnkuvVFZE8zmgzI=: CN=ISRG Root X2,O=Internet Security Research Group,C=US
                                                                             sha256/C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=: CN=ISRG Root X1,O=Internet Security Research Group,C=US
                                                                           Pinned certificates for www.speedtest.net:
                                                                             sha256/AwZuXoBD+efE/tN4oCYOJ3EY+PNbizd4riD5eAWG3tQ=
                                                                             sha256/FEzVOUp4dF3gI0ZVPRJhFbSJVXR+uQmMH65xhs1glH4=
                                                                             sha256/Y9mvm0exBk1JoQ57f9Vm28jKo5lFm/woKcVxrYxu80o=`
                                                                             
Is there something to do to fix it?

**Comment by faisal-3techsoft** [comment]
just comment out 
"    /*   val certificatePinner = CertificatePinner.Builder()
                   .add("www.speedtest.net","sha256/AwZuXoBD+efE/tN4oCYOJ3EY+PNbizd4riD5eAWG3tQ=")
                   .add("www.speedtest.net","sha256/FEzVOUp4dF3gI0ZVPRJhFbSJVXR+uQmMH65xhs1glH4=")
                   .add("www.speedtest.net","sha256/Y9mvm0exBk1JoQ57f9Vm28jKo5lFm/woKcVxrYxu80o=")
                   .build()*/"
and this line " .certificatePinner(certificatePinner)"
in Server class and works for me

**Comment by farimarwat** [comment]
Fixed
